### ISSUE TITLE
Add Confluent Kafka Connect base image to docker swarm and create and publish docker image for the Kafka Connect services we need

### ISSUE THREAD

**Issue by niem94** [JuiceInTheOven/EcoBeach#48]
https://hub.docker.com/r/confluentinc/cp-kafka-connect

Just researched this. We need to add the above image to our docker swarm to support Kafka Connect services from confluent, and then we need to create a docker image that installs the different Kafka Connect services that we need like so (the services are just examples):

```docker
FROM confluentinc/cp-kafka-connect-base:6.2.1

RUN   confluent-hub install --no-prompt hpgrahsl/kafka-connect-mongodb:1.1.0 \
   && confluent-hub install --no-prompt microsoft/kafka-connect-iothub:0.6 \
   && confluent-hub install --no-prompt wepay/kafka-connect-bigquery:1.1.0
```
Source (https://docs.confluent.io/platform/current/installation/docker/development.html#extending-images)

@jazerix maybe we should look at this together as I have the task of adding the HDFS connector and you the distributed database connector, and we basically have to write the same code :-)

**Comment by jazerix** [comment]
They have a bridge project that allows you to add connectors without having to build a completely new docker image, I'll probably opt for that initially
